[NbConvertApp] Converting notebook /project/mang/users/tosin/GLP/lpn_for_nonconvex_control/exps/exp_4_1_2_quadratic_16D copy.ipynb to notebook
Traceback (most recent call last):
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/bin/jupyter-nbconvert", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/jupyter_core/application.py", line 284, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
    ~~~~~~~~~^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/nbconvertapp.py", line 420, in start
    self.convert_notebooks()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/nbconvertapp.py", line 597, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        notebook_filename, resources, input_buffer=input_buffer
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/nbconvertapp.py", line 487, in export_single_notebook
    output, resources = self.exporter.from_filename(
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        notebook_filename, resources=resources
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/exporters/exporter.py", line 201, in from_filename
    return self.from_file(f, resources=resources, **kw)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/exporters/exporter.py", line 220, in from_file
    return self.from_notebook_node(
           ~~~~~~~~~~~~~~~~~~~~~~~^
        nbformat.read(file_stream, as_version=4), resources=resources, **kw
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/exporters/notebook.py", line 36, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/exporters/exporter.py", line 154, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/exporters/exporter.py", line 353, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
                ~~~~~~~~~~~~^^^^^^^^^^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/preprocessors/base.py", line 48, in __call__
    return self.preprocess(nb, resources)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/preprocessors/execute.py", line 103, in preprocess
    self.preprocess_cell(cell, resources, index)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbconvert/preprocessors/execute.py", line 124, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/project/mang/users/andreas/mamba/mamba_envs/env_lpn/lpn_env/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# L2 loss -- Plot
plot_all_quadratic_l1(lpn_model_quad_l1, a_exp, spacing, INVERT_MODE, dim_exp)
------------------


[31m---------------------------------------------------------------------------[39m
[31mNameError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[8][39m[32m, line 2[39m
[32m      1[39m [38;5;66;03m# L2 loss -- Plot[39;00m
[32m----> [39m[32m2[39m plot_all_quadratic_l1([43mlpn_model_quad_l1[49m, a_exp, spacing, INVERT_MODE, dim_exp)

[31mNameError[39m: name 'lpn_model_quad_l1' is not defined

[NbConvertApp] Converting notebook /project/mang/users/tosin/GLP/lpn_for_nonconvex_control/exps/exp_4_1_2_quadratic_32D.ipynb to notebook
[NbConvertApp] Writing 659972 bytes to /project/mang/users/tosin/GLP/lpn_for_nonconvex_control/exps/exp_4_1_2_quadratic_32D.ipynb
[NbConvertApp] Converting notebook /project/mang/users/tosin/GLP/lpn_for_nonconvex_control/exps/exp_4_1_2_quadratic_64D.ipynb to notebook
slurmstepd: error: *** JOB 16137257 ON compute-0-39 CANCELLED AT 2025-10-29T14:42:24 DUE TO TIME LIMIT ***
